### ISSUE TITLE
Idling after ctrl-R

### ISSUE THREAD

**Issue by yvesalexandre** [smathot/gedit-plugin-ipython#1]
Thanks this is such a useful and clean plugin!

Using IPython 0.13.2 and gedit 3.6.2 when I ctrl-R it copies the text correctly but I need to go back to the console and press enter to get the last line executed.

Looking at the ipython manual they seem to recommend using the magic command %paste.

In [2]: hello = 'test'
print hello
Out[2]: 
test

In [2]:

**Comment by smathot** [comment]
Project moved to https://gitlab.com/mcepl/gedit-plugin-ipython
